name: Grocy
version: "1.0.0"
slug: grocy
description: ERP beyond your fridge - Grocy is a web-based self-hosted groceries & household management solution
url: https://github.com/grocy/grocy
arch:
  - aarch64
  - amd64
  - armv7
init: false
ingress: true
ingress_port: 80
panel_icon: mdi:fridge-outline
panel_title: Grocy
startup: services
boot: auto
map:
  - config:rw
options:
  culture: en
  currency: USD
  tz: America/New_York
schema:
  culture: str
  currency: str
  tz: str
